/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetopoo;

/**
 *
 * @author victo
 */
public class JFAluno extends javax.swing.JFrame {

    String Usuario;
    JFLogin jflogin = new JFLogin();
    
    public JFAluno(String Usuario) {
        initComponents();
        this.Usuario = Usuario;
    }
    
    public JFAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBBoletim = new javax.swing.JButton();
        jBSimulados = new javax.swing.JButton();
        jPanelAluno = new javax.swing.JPanel();
        jLabelIconeAluno = new javax.swing.JLabel();
        jLNomeAluno = new javax.swing.JLabel();
        jLBemVindo = new javax.swing.JLabel();
        jLUsuarioAluno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Aluno");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jBBoletim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopoo/Icones/exame.png"))); // NOI18N
        jBBoletim.setText("Boletim");
        jBBoletim.setFocusPainted(false);
        jBBoletim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBBoletim.setIconTextGap(25);
        jBBoletim.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBSimulados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopoo/Icones/lista-de-controle (1).png"))); // NOI18N
        jBSimulados.setText("Simulados");
        jBSimulados.setFocusPainted(false);
        jBSimulados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSimulados.setIconTextGap(25);
        jBSimulados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBSimulados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSimuladosActionPerformed(evt);
            }
        });

        jPanelAluno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.lightGray));

        jLabelIconeAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconeAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopoo/Icones/aluna_1.png"))); // NOI18N
        jLabelIconeAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelIconeAluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLNomeAluno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLBemVindo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLBemVindo.setText("Bem vindo,");

        jLabel1.setText("Usuario:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelAlunoLayout = new javax.swing.GroupLayout(jPanelAluno);
        jPanelAluno.setLayout(jPanelAlunoLayout);
        jPanelAlunoLayout.setHorizontalGroup(
            jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlunoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelIconeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlunoLayout.createSequentialGroup()
                        .addComponent(jLBemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAlunoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLUsuarioAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAlunoLayout.setVerticalGroup(
            jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlunoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelIconeAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(jPanelAlunoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLNomeAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLUsuarioAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopoo/Icones/seta-para-a-esquerda.png"))); // NOI18N
        jBSair.setFocusPainted(false);
        jBSair.setMaximumSize(new java.awt.Dimension(16, 16));
        jBSair.setMinimumSize(new java.awt.Dimension(16, 16));
        jBSair.setPreferredSize(new java.awt.Dimension(22, 22));
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 160, Short.MAX_VALUE)
                        .addComponent(jBBoletim, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jBSimulados, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jPanelAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jPanelAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSimulados, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBoletim, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSimuladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSimuladosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSimuladosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        jLNomeAluno.setText(Usuario);
        
        for (Alunos elementoAlunos: Alunos.ListaAlunos){
            if(elementoAlunos.getRA().equals(Usuario)){
                jLNomeAluno.setText(elementoAlunos.getNomeAluno());
                jLUsuarioAluno.setText(elementoAlunos.getRA());
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);
        jLNomeAluno.setText(Usuario);
        
        for (Alunos elementoAlunos: Alunos.ListaAlunos){
            if(elementoAlunos.getRA().equals(Usuario)){
                jLNomeAluno.setText(elementoAlunos.getNomeAluno());
                jLUsuarioAluno.setText(elementoAlunos.getRA());
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        dispose();
        jflogin.setVisible(true);
    }//GEN-LAST:event_jBSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBoletim;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSimulados;
    private javax.swing.JLabel jLBemVindo;
    private javax.swing.JLabel jLNomeAluno;
    private javax.swing.JLabel jLUsuarioAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIconeAluno;
    private javax.swing.JPanel jPanelAluno;
    // End of variables declaration//GEN-END:variables
}
