/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetopoo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class JFCadastrarTurmas extends javax.swing.JFrame {

    String Usuario;
    GerenciarProfessores gerenciarprofessores = new GerenciarProfessores();
    GerenciarAlunos gerenciaralunos = new GerenciarAlunos();
    GerenciarTurmas gerenciarturmas = new GerenciarTurmas();
    JFGerenciarTurmas jfgerenciarturmas;
    private DefaultTableModel tableModel;
    private DefaultTableModel tableModel2;
    
    public JFCadastrarTurmas() {
        initComponents();
        
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nome");
        tableModel.addColumn("CPF");
        tableModel.addColumn("Disciplina");
        jTableProfessores.setModel(tableModel);
        tableModel.setRowCount(0);
        
        tableModel2 = new DefaultTableModel();
        tableModel2.addColumn("Nome");
        tableModel2.addColumn("RA");
        jTableAlunos.setModel(tableModel2);
        tableModel2.setRowCount(0); 
    }
    
    public JFCadastrarTurmas(String Usuario) {
        initComponents();
        this.Usuario = Usuario;
        
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nome");
        tableModel.addColumn("CPF");
        tableModel.addColumn("Disciplina");
        jTableProfessores.setModel(tableModel);
        tableModel.setRowCount(0);
        
        tableModel2 = new DefaultTableModel();
        tableModel2.addColumn("Nome");
        tableModel2.addColumn("RA");
        jTableAlunos.setModel(tableModel2);
        tableModel2.setRowCount(0); 
    }

    public void limpaTabelaProfessores(){
        ((DefaultTableModel) jTableProfessores.getModel()).setRowCount(0);
    }
    
    public void limpaTabelaAlunos(){
        ((DefaultTableModel) jTableAlunos.getModel()).setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNomeTurma = new javax.swing.JLabel();
        jTCadastrarNomeTurma = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfessores = new javax.swing.JTable();
        jLCPFProfessor = new javax.swing.JLabel();
        jTAdicionarCPFProfessor = new javax.swing.JTextField();
        jBAdicionarCPFProfessor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAlunos = new javax.swing.JTable();
        jLRAAluno = new javax.swing.JLabel();
        jTAdicionarRAAluno = new javax.swing.JTextField();
        jBAdicionarRAAluno = new javax.swing.JButton();
        jBCadastrarTurma = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLNomeTurma.setText("Nome da turma");

        jTCadastrarNomeTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCadastrarNomeTurmaActionPerformed(evt);
            }
        });

        jTableProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProfessores);

        jLCPFProfessor.setText("Digite o CPF do professor");

        jTAdicionarCPFProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAdicionarCPFProfessorActionPerformed(evt);
            }
        });

        jBAdicionarCPFProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopoo/Icones/adicionar-usuario16px.png"))); // NOI18N
        jBAdicionarCPFProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarCPFProfessorActionPerformed(evt);
            }
        });

        jTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableAlunos);

        jLRAAluno.setText("Digite o RA do aluno");

        jTAdicionarRAAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAdicionarRAAlunoActionPerformed(evt);
            }
        });

        jBAdicionarRAAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopoo/Icones/adicionar-usuario16px.png"))); // NOI18N
        jBAdicionarRAAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarRAAlunoActionPerformed(evt);
            }
        });

        jBCadastrarTurma.setText("Cadastrar");
        jBCadastrarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarTurmaActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLNomeTurma)
                        .addGap(29, 29, 29)
                        .addComponent(jTCadastrarNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jBCadastrarTurma)
                        .addGap(119, 119, 119)
                        .addComponent(jBVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLRAAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTAdicionarRAAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAdicionarRAAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLCPFProfessor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTAdicionarCPFProfessor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBAdicionarCPFProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeTurma)
                    .addComponent(jTCadastrarNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCPFProfessor)
                    .addComponent(jTAdicionarCPFProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdicionarCPFProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRAAluno)
                    .addComponent(jTAdicionarRAAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdicionarRAAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarTurma)
                    .addComponent(jBVoltar))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTAdicionarCPFProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAdicionarCPFProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAdicionarCPFProfessorActionPerformed

    private void jTAdicionarRAAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAdicionarRAAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAdicionarRAAlunoActionPerformed

    private void jTCadastrarNomeTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCadastrarNomeTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCadastrarNomeTurmaActionPerformed

    private void jBAdicionarCPFProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarCPFProfessorActionPerformed
        
        String CPFProfessor = jTAdicionarCPFProfessor.getText();
        Boolean Find = false;
        
        for (Professores elementoProfessores: Professores.ListaProfessores) {
            if(CPFProfessor.equals(elementoProfessores.getCPF())){
                tableModel.addRow(new Object[]{elementoProfessores.getNomeProfessor(),elementoProfessores.getCPF(),elementoProfessores.getDisciplinaProfessor().toString().replace("Materia: ", "")});
                Find=true;
            }
        }
        
        if(!Find){
            JOptionPane.showMessageDialog(null, "Houve um erro ao adicionar o professor a turma. Professor nao encontrado no sistema", "Cadastro de Turmas", JOptionPane.ERROR_MESSAGE);
        }
        
        jTAdicionarCPFProfessor.setText("");
        
    }//GEN-LAST:event_jBAdicionarCPFProfessorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null); 
    }//GEN-LAST:event_formWindowActivated

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        
        jfgerenciarturmas = new JFGerenciarTurmas(Usuario);
        dispose();
        jfgerenciarturmas.setVisible(true);
        
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBAdicionarRAAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarRAAlunoActionPerformed
        
        String RAAluno = jTAdicionarRAAluno.getText();
        Boolean Find = false;
        
        for (Alunos elementoAlunos: Alunos.ListaAlunos) {
            if(RAAluno.equals(elementoAlunos.getRA())){
                tableModel2.addRow(new Object[]{elementoAlunos.getNomeAluno(),elementoAlunos.getRA()});
                Find = true;
            }
        }
        
        if(!Find){
            JOptionPane.showMessageDialog(null, "Houve um erro ao adicionar o aluno a turma. Aluno nao encontrado no sistema", "Cadastro de Turmas", JOptionPane.ERROR_MESSAGE);
        }
        
        jTAdicionarRAAluno.setText("");
        
    }//GEN-LAST:event_jBAdicionarRAAlunoActionPerformed

    private void jBCadastrarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarTurmaActionPerformed
        
        String NomeTurma = jTCadastrarNomeTurma.getText();
        
        int totalRowsProfessores = jTableProfessores.getRowCount();
        ArrayList<Professores> professoresTurma = new ArrayList<>();
        int totalRowsAlunos = jTableAlunos.getRowCount();
        ArrayList<Alunos> AlunosTurma = new ArrayList<>();
        
        for (int linha = 0; linha < totalRowsProfessores; linha++) {
            String CPFProfessor = jTableProfessores.getValueAt(linha, 1).toString();
            professoresTurma.add(gerenciarprofessores.consultarProfessores(CPFProfessor));
        }
        
        for (int linha = 0; linha < totalRowsAlunos; linha++) {
            String RAAlunos = jTableAlunos.getValueAt(linha, 1).toString();
            AlunosTurma.add(gerenciaralunos.consultarAlunos(RAAlunos));
        }
        
        gerenciarturmas.cadastrarTurma(NomeTurma, professoresTurma, AlunosTurma);
        limpaTabelaProfessores();
        limpaTabelaAlunos();
        jTCadastrarNomeTurma.setText("");
        jTAdicionarCPFProfessor.setText("");
        jTAdicionarRAAluno.setText("");
       
        
    }//GEN-LAST:event_jBCadastrarTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCadastrarTurmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionarCPFProfessor;
    private javax.swing.JButton jBAdicionarRAAluno;
    private javax.swing.JButton jBCadastrarTurma;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLCPFProfessor;
    private javax.swing.JLabel jLNomeTurma;
    private javax.swing.JLabel jLRAAluno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTAdicionarCPFProfessor;
    private javax.swing.JTextField jTAdicionarRAAluno;
    private javax.swing.JTextField jTCadastrarNomeTurma;
    private javax.swing.JTable jTableAlunos;
    private javax.swing.JTable jTableProfessores;
    // End of variables declaration//GEN-END:variables
}
