/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetopoo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author victo
 */
public class JFCadastrarNotas extends javax.swing.JFrame {

    String Usuario;
    JFNotas jfnotas;
    Notas notas = new Notas();
    
    public JFCadastrarNotas(String Usuario) {
        initComponents();
        this.Usuario = Usuario;
    }
    
    public JFCadastrarNotas() {
        initComponents();
    }
    
    public class ExceptionPersonalizada extends NumberFormatException{
        
        public ExceptionPersonalizada(String mensagem){
            super(mensagem);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNota = new javax.swing.JLabel();
        jTFNota = new javax.swing.JTextField();
        jCBAluno = new javax.swing.JComboBox<>();
        jBConfirmar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLNota.setText("Nota");

        jCBAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno" }));

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCBAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jBConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jBCancelar)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jCBAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNota)
                    .addComponent(jTFNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConfirmar)
                    .addComponent(jBCancelar))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.setLocationRelativeTo(null);
        ArrayList<String> TurmasProfessor = new ArrayList<>();
        
        for (Turmas elementoTurmas: Turmas.ListaTurmas) {
            
            for (Professores elementoProfessor: elementoTurmas.getListaProfessores()) {
                
                if (elementoProfessor.getCPF().equals(Usuario)) {
                    TurmasProfessor.add(elementoTurmas.getNomeTurma());
                }
                
            }
            
            for (String elementoTurmasProfessor : TurmasProfessor) {
                
                if (elementoTurmasProfessor.equals(elementoTurmas.getNomeTurma())) {
                    
                    for (Alunos elementoAlunos : elementoTurmas.getListaAlunos()) {
                        
                        jCBAluno.addItem(elementoAlunos.getRA());
                        
                    }
                    
                }
                
            }
            
        }
        
        if (jCBAluno.getItemCount()>1) {
            jCBAluno.removeItemAt(0);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        jfnotas = new JFNotas(Usuario);
        dispose();
        jfnotas.setVisible(true);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        
        String RA = jCBAluno.getSelectedItem().toString();
        float Nota= 0.0f;
        
        try {
            
            String NotaString = jTFNota.getText();
            
            if (NotaString.matches("\\d+(\\.\\d+)?")) {
                
                Nota = Float.parseFloat(NotaString);
                notas.cadastrarNotas(Usuario, RA, Nota);
                JOptionPane.showMessageDialog(null, "Nota cadastrada com sucesso!", "Cadastro de Notas", JOptionPane.INFORMATION_MESSAGE);
                
            }else{
                throw new ExceptionPersonalizada("Erro nota\n");
            }
            
        } catch (ExceptionPersonalizada e) {
            System.out.print("Exception Personalizada: "+e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar nota. Insira apenas numeros.", "Cadastro de Notas", JOptionPane.ERROR_MESSAGE);

        }
        
        jTFNota.setText("");
        
    }//GEN-LAST:event_jBConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCadastrarNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JComboBox<String> jCBAluno;
    private javax.swing.JLabel jLNota;
    private javax.swing.JTextField jTFNota;
    // End of variables declaration//GEN-END:variables
}
