/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetopoo;
/**
 *
 * @author victo
 */
public class JFDiretor extends javax.swing.JFrame {

    Alunos alunos = new Alunos();
    Professores professores = new Professores();
    JFGerenciarProfessores jfgerenciarprofessores;
    JFGerenciarDisciplinas jfgerenciardisciplinas;
    JFGerenciarAlunos jfgerenciaralunos;
    JFGerenciarTurmas jfgerenciarturmas;
    JFGerenciarEventos jfgerenciareventos;
    JFLogin jflogin = new JFLogin();
    
    String Usuario;
   

    public JFDiretor(String Usuario) {
        initComponents();
        this.Usuario = Usuario;
    }
    
    public JFDiretor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGerenciarProfessores = new javax.swing.JButton();
        jBGerenciarAlunos = new javax.swing.JButton();
        jBGerenciarDisciplinas = new javax.swing.JButton();
        jBPalestras = new javax.swing.JButton();
        jPanelDiretor = new javax.swing.JPanel();
        jLIconeDiretor = new javax.swing.JLabel();
        jLNomeUsuarioDiretor = new javax.swing.JLabel();
        jLBemVindo = new javax.swing.JLabel();
        jBGerenciarTurmas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Diretor");
        setLocation(new java.awt.Point(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jBGerenciarProfessores.setText("Gerenciar Professores");
        jBGerenciarProfessores.setToolTipText("");
        jBGerenciarProfessores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBGerenciarProfessores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGerenciarProfessores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBGerenciarProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerenciarProfessoresActionPerformed(evt);
            }
        });

        jBGerenciarAlunos.setText("Gerenciar Alunos");
        jBGerenciarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerenciarAlunosActionPerformed(evt);
            }
        });

        jBGerenciarDisciplinas.setText("Gerenciar Disciplinas");
        jBGerenciarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerenciarDisciplinasActionPerformed(evt);
            }
        });

        jBPalestras.setText("Eventos");
        jBPalestras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPalestras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBPalestras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPalestrasActionPerformed(evt);
            }
        });

        jPanelDiretor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.lightGray));

        jLIconeDiretor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIconeDiretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopoo/Icones/Diretor64px.png"))); // NOI18N
        jLIconeDiretor.setText("ICONE TOP");
        jLIconeDiretor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLIconeDiretor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLBemVindo.setText("Bem vindo,");

        javax.swing.GroupLayout jPanelDiretorLayout = new javax.swing.GroupLayout(jPanelDiretor);
        jPanelDiretor.setLayout(jPanelDiretorLayout);
        jPanelDiretorLayout.setHorizontalGroup(
            jPanelDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiretorLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLIconeDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLNomeUsuarioDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanelDiretorLayout.setVerticalGroup(
            jPanelDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiretorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLIconeDiretor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(jPanelDiretorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNomeUsuarioDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBemVindo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBGerenciarTurmas.setText("Gerenciar Turmas");
        jBGerenciarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerenciarTurmasActionPerformed(evt);
            }
        });

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(67, Short.MAX_VALUE)
                        .addComponent(jPanelDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jBGerenciarProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jBGerenciarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBGerenciarDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jBPalestras, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(jBGerenciarTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanelDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBGerenciarAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBGerenciarDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBGerenciarProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBGerenciarTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPalestras, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGerenciarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerenciarDisciplinasActionPerformed
        jfgerenciardisciplinas = new JFGerenciarDisciplinas(Usuario);
        dispose();
        jfgerenciardisciplinas.setVisible(true);
    }//GEN-LAST:event_jBGerenciarDisciplinasActionPerformed

    private void jBGerenciarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerenciarAlunosActionPerformed
        jfgerenciaralunos = new JFGerenciarAlunos(Usuario);
        dispose();
        jfgerenciaralunos.setVisible(true);
    }//GEN-LAST:event_jBGerenciarAlunosActionPerformed

    private void jBGerenciarProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerenciarProfessoresActionPerformed
        
        jfgerenciarprofessores = new JFGerenciarProfessores(Usuario);
        dispose();
        jfgerenciarprofessores.setVisible(true);
        
    }//GEN-LAST:event_jBGerenciarProfessoresActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        jLNomeUsuarioDiretor.setText(Usuario);
        System.out.print("Usuario Diretor: " + Usuario + "\n");
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jLNomeUsuarioDiretor.setText(Usuario);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void jBGerenciarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerenciarTurmasActionPerformed
        jfgerenciarturmas = new JFGerenciarTurmas(Usuario);
        dispose();
        jfgerenciarturmas.setVisible(true);
    }//GEN-LAST:event_jBGerenciarTurmasActionPerformed

    private void jBPalestrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPalestrasActionPerformed
        jfgerenciareventos = new JFGerenciarEventos(Usuario);
        dispose();
        jfgerenciareventos.setVisible(true);
    }//GEN-LAST:event_jBPalestrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        jflogin.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDiretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGerenciarAlunos;
    private javax.swing.JButton jBGerenciarDisciplinas;
    private javax.swing.JButton jBGerenciarProfessores;
    private javax.swing.JButton jBGerenciarTurmas;
    private javax.swing.JButton jBPalestras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLBemVindo;
    private javax.swing.JLabel jLIconeDiretor;
    private javax.swing.JLabel jLNomeUsuarioDiretor;
    private javax.swing.JPanel jPanelDiretor;
    // End of variables declaration//GEN-END:variables
}
