/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetopoo;

import javax.swing.DefaultCellEditor;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author victo
 */
public class JFGerenciarTurmas extends javax.swing.JFrame {

    String Usuario;
    JFCadastrarTurmas jfcadastrarturmas;
    private DefaultTableModel tableModel;
    
    public JFGerenciarTurmas() {
        initComponents();
        this.Usuario = Usuario;
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nome da Turma");
        tableModel.addColumn("Alunos");
        tableModel.addColumn("Professores");
        jTableTurmas.setModel(tableModel);
        tableModel.setRowCount(0);
    }

    public JFGerenciarTurmas(String Usuario) {
        initComponents();
        this.Usuario = Usuario;
        this.Usuario = Usuario;
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nome da Turma");
        tableModel.addColumn("Alunos");
        tableModel.addColumn("Professores");
        jTableTurmas.setModel(tableModel);
        tableModel.setRowCount(0);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCAlunos = new javax.swing.JComboBox<>();
        jCProfessores = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTurmas = new javax.swing.JTable();
        jTPesquisarTurmas = new javax.swing.JTextField();
        jBPesquisarTurmas = new javax.swing.JButton();
        jBCadastrarTurmas = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jBRemover = new javax.swing.JButton();

        jCAlunos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCProfessores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTableTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome da Turma"
            }
        ));
        jScrollPane1.setViewportView(jTableTurmas);

        jTPesquisarTurmas.setText("Digite o nome da turma");
        jTPesquisarTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPesquisarTurmasMouseClicked(evt);
            }
        });
        jTPesquisarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPesquisarTurmasActionPerformed(evt);
            }
        });

        jBPesquisarTurmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopoo/Icones/procurar16px.png"))); // NOI18N
        jBPesquisarTurmas.setMaximumSize(new java.awt.Dimension(16, 18));
        jBPesquisarTurmas.setMinimumSize(new java.awt.Dimension(16, 18));
        jBPesquisarTurmas.setPreferredSize(new java.awt.Dimension(23, 23));
        jBPesquisarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarTurmasActionPerformed(evt);
            }
        });

        jBCadastrarTurmas.setText("Cadastrar");
        jBCadastrarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarTurmasActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBRemover.setText("Remover");
        jBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTPesquisarTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPesquisarTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBCadastrarTurmas)
                        .addGap(23, 23, 23)
                        .addComponent(jBRemover)
                        .addGap(18, 18, 18)
                        .addComponent(jBVoltar)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPesquisarTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarTurmas)
                    .addComponent(jBVoltar)
                    .addComponent(jBRemover))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPesquisarTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPesquisarTurmasMouseClicked
        jTPesquisarTurmas.setText(null);
    }//GEN-LAST:event_jTPesquisarTurmasMouseClicked

    private void jBPesquisarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarTurmasActionPerformed

        //String NomeDisciplina = jTPesquisarTurmas.getText();
        //System.out.println("Disciplina pesquisada: " + NomeDisciplina);

        //limpaTabela();

        //for (Disciplinas elementoDisciplinas: Disciplinas.ListaDisciplinas) {
            //if (elementoDisciplinas.getNomeDisciplina().equalsIgnoreCase(NomeDisciplina)) {
            //    tableModel.addRow(new Object[]{elementoDisciplinas.getNomeDisciplina()});
            //}
        //}

    }//GEN-LAST:event_jBPesquisarTurmasActionPerformed

    private void jBCadastrarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarTurmasActionPerformed
        jfcadastrarturmas = new JFCadastrarTurmas(Usuario);
        dispose();
        jfcadastrarturmas.setVisible(true);
    }//GEN-LAST:event_jBCadastrarTurmasActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        JFDiretor jfdiretor = new JFDiretor(Usuario);
        dispose();
        jfdiretor.setVisible(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverActionPerformed

        //int linhaselecionada = jTableTurmas.getSelectedRow();

        //String NomeDisciplina = jTableTurmas.getValueAt(linhaselecionada, 0).toString();
       // ((DefaultTableModel) jTableTurmas.getModel()).removeRow(linhaselecionada);

       // gerenciardisciplinas.removerDisciplinas(NomeDisciplina);

    }//GEN-LAST:event_jBRemoverActionPerformed

    private void jTPesquisarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPesquisarTurmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesquisarTurmasActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        this.setLocationRelativeTo(null); 
        
        TableColumn column1 = jTableTurmas.getColumnModel().getColumn(2);
        column1.setCellEditor(new DefaultCellEditor(jCAlunos));
        
        TableColumn column2 = jTableTurmas.getColumnModel().getColumn(3);
        column2.setCellEditor(new DefaultCellEditor(jCProfessores));
        
        for (Turmas elementoTurmas: Turmas.ListaTurmas) {
            tableModel.addRow(new Object[]{elementoTurmas.getNomeTurma(),elementoTurmas.getListaAlunosTurmaString(),elementoTurmas.getListaProfessoresTurmaString()});
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGerenciarTurmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarTurmas;
    private javax.swing.JButton jBPesquisarTurmas;
    private javax.swing.JButton jBRemover;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox<String> jCAlunos;
    private javax.swing.JComboBox<String> jCProfessores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTPesquisarTurmas;
    private javax.swing.JTable jTableTurmas;
    // End of variables declaration//GEN-END:variables
}
