/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetopoo;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author victo
 */
public class JFGerenciarTurmas extends javax.swing.JFrame {

    String Usuario;
    JFCadastrarTurmas jfcadastrarturmas;
    GerenciarTurmas gerenciarturmas = new GerenciarTurmas();
    private DefaultTableModel tableModel1;
    private DefaultTableModel tableModel2;
     
    
    public JFGerenciarTurmas() {
        initComponents();
        this.Usuario = Usuario;
        
        tableModel1 = new DefaultTableModel();
        tableModel1.addColumn("Nome");
        tableModel1.addColumn("RA");
        jTableAlunos.setModel(tableModel1);
        tableModel1.setRowCount(0);
        
        tableModel2 = new DefaultTableModel();
        tableModel2.addColumn("Nome");
        tableModel2.addColumn("CPF");
        tableModel2.addColumn("Disciplina");
        jTableProfessores.setModel(tableModel2);
        tableModel2.setRowCount(0);
    }

    public JFGerenciarTurmas(String Usuario) {
        initComponents();
        this.Usuario = Usuario;
        this.Usuario = Usuario;
        tableModel1 = new DefaultTableModel();
        tableModel1.addColumn("Nome");
        tableModel1.addColumn("RA");
        jTableAlunos.setModel(tableModel1);
        tableModel1.setRowCount(0);
        
        tableModel2 = new DefaultTableModel();
        tableModel2.addColumn("Nome");
        tableModel2.addColumn("CPF");
        tableModel2.addColumn("Disciplina");
        jTableProfessores.setModel(tableModel2);
        tableModel2.setRowCount(0);
        
    }
    
    public void limpaTabelaAlunos(){
        ((DefaultTableModel) jTableAlunos.getModel()).setRowCount(0);
    }
    
        public void limpaTabelaProfessores(){
        ((DefaultTableModel) jTableProfessores.getModel()).setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCAlunos = new javax.swing.JComboBox<>();
        jCProfessores = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlunos = new javax.swing.JTable();
        jBCadastrarTurmas = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jBRemover = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProfessores = new javax.swing.JTable();
        jCNomeTurma = new javax.swing.JComboBox<>();

        jCAlunos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCProfessores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "RA"
            }
        ));
        jScrollPane1.setViewportView(jTableAlunos);

        jBCadastrarTurmas.setText("Cadastrar");
        jBCadastrarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarTurmasActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBRemover.setText("Remover");
        jBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverActionPerformed(evt);
            }
        });

        jTableProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Disciplina"
            }
        ));
        jScrollPane2.setViewportView(jTableProfessores);

        jCNomeTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome da Turma" }));
        jCNomeTurma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCNomeTurmaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jBCadastrarTurmas)
                        .addGap(23, 23, 23)
                        .addComponent(jBRemover)
                        .addGap(18, 18, 18)
                        .addComponent(jBVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jCNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jCNomeTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarTurmas)
                    .addComponent(jBVoltar)
                    .addComponent(jBRemover))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarTurmasActionPerformed
        jfcadastrarturmas = new JFCadastrarTurmas(Usuario);
        dispose();
        jfcadastrarturmas.setVisible(true);
    }//GEN-LAST:event_jBCadastrarTurmasActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        JFDiretor jfdiretor = new JFDiretor(Usuario);
        dispose();
        jfdiretor.setVisible(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverActionPerformed

        String nomeTurma = jCNomeTurma.getSelectedItem().toString();
        gerenciarturmas.removerTurma(nomeTurma);
       
        limpaTabelaAlunos();
        limpaTabelaProfessores();
        jCNomeTurma.removeItemAt(jCNomeTurma.getSelectedIndex());
       
        JOptionPane.showMessageDialog(null, "Turma removida com sucesso no sistema.", "Gerenciar Turmas", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jBRemoverActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        this.setLocationRelativeTo(null); 
        
        for (Turmas elementoTurmas: Turmas.ListaTurmas) {
            jCNomeTurma.addItem(elementoTurmas.getNomeTurma());
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void jCNomeTurmaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCNomeTurmaItemStateChanged
        
        String NomeTurma = jCNomeTurma.getSelectedItem().toString();
        
        jCNomeTurma.addItemListener(new ItemListener(){
            
            public void itemStateChanged(ItemEvent e){
                
                if(e.getStateChange()== ItemEvent.SELECTED) {
                    for (Turmas elementoTurma: Turmas.ListaTurmas) {
            
                        if (elementoTurma.getNomeTurma().equals(NomeTurma)) {

                            for (Alunos elementoAluno : elementoTurma.getListaAlunos()) {
                                tableModel1.addRow(new Object[]{elementoAluno.getNomeAluno(), elementoAluno.getRA()});
                            }

                            for (Professores elementoProfessores : elementoTurma.getListaProfessores()) {
                                tableModel2.addRow(new Object[]{elementoProfessores.getNomeProfessor(), elementoProfessores.getCPF(), elementoProfessores.getDisciplinaProfessor()});
                            }

                        }
                    }
                }
            }
        });
        

        
        
    }//GEN-LAST:event_jCNomeTurmaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGerenciarTurmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarTurmas;
    private javax.swing.JButton jBRemover;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox<String> jCAlunos;
    private javax.swing.JComboBox<String> jCNomeTurma;
    private javax.swing.JComboBox<String> jCProfessores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAlunos;
    private javax.swing.JTable jTableProfessores;
    // End of variables declaration//GEN-END:variables
}
