/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetopoo;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class JFGerenciarDisciplinas extends javax.swing.JFrame {

    String Usuario;
    JFCadastrarDisciplinas jfcadastrardisciplinas;
    GerenciarDisciplinas gerenciardisciplinas = new GerenciarDisciplinas();
    private DefaultTableModel tableModel;
    
    public JFGerenciarDisciplinas() {
        initComponents();
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Disciplinas");
        jTableDisciplinas.setModel(tableModel);
        tableModel.setRowCount(0);
    }
    
    public JFGerenciarDisciplinas(String Usuario) {
        initComponents();
        this.Usuario = Usuario;
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Disciplinas");
        jTableDisciplinas.setModel(tableModel);
        tableModel.setRowCount(0);
    }

    public void limpaTabela(){
        ((DefaultTableModel) jTableDisciplinas.getModel()).setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDisciplinas = new javax.swing.JTable();
        jTPesquisarDisciplinas = new javax.swing.JTextField();
        jBPesquisarDisciplinas = new javax.swing.JButton();
        jBCadastrarDisciplina = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jBRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTableDisciplinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDisciplinasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDisciplinas);

        jTPesquisarDisciplinas.setText("Digite o nome da materia");
        jTPesquisarDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPesquisarDisciplinasMouseClicked(evt);
            }
        });
        jTPesquisarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPesquisarDisciplinasActionPerformed(evt);
            }
        });

        jBPesquisarDisciplinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetopoo/Icones/procurar16px.png"))); // NOI18N
        jBPesquisarDisciplinas.setMaximumSize(new java.awt.Dimension(16, 18));
        jBPesquisarDisciplinas.setMinimumSize(new java.awt.Dimension(16, 18));
        jBPesquisarDisciplinas.setPreferredSize(new java.awt.Dimension(23, 23));
        jBPesquisarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarDisciplinasActionPerformed(evt);
            }
        });

        jBCadastrarDisciplina.setText("Cadastrar");
        jBCadastrarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarDisciplinaActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBRemover.setText("Remover");
        jBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTPesquisarDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPesquisarDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jBCadastrarDisciplina)
                .addGap(23, 23, 23)
                .addComponent(jBRemover)
                .addGap(18, 18, 18)
                .addComponent(jBVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPesquisarDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarDisciplina)
                    .addComponent(jBVoltar)
                    .addComponent(jBRemover))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPesquisarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPesquisarDisciplinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesquisarDisciplinasActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        JFDiretor jfdiretor = new JFDiretor(Usuario);
        dispose();
        jfdiretor.setVisible(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBCadastrarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarDisciplinaActionPerformed
        jfcadastrardisciplinas = new JFCadastrarDisciplinas(Usuario);
        dispose();
        jfcadastrardisciplinas.setVisible(true);
    }//GEN-LAST:event_jBCadastrarDisciplinaActionPerformed

    private void jTPesquisarDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPesquisarDisciplinasMouseClicked
        jTPesquisarDisciplinas.setText(null);
    }//GEN-LAST:event_jTPesquisarDisciplinasMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null); 
        
        for (Disciplinas elementoDisciplinas: Disciplinas.ListaDisciplinas) {
            tableModel.addRow(new Object[]{elementoDisciplinas.getNomeDisciplina()});
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void jBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverActionPerformed

        int linhaselecionada = jTableDisciplinas.getSelectedRow();
        
        String NomeDisciplina = jTableDisciplinas.getValueAt(linhaselecionada, 0).toString();
        ((DefaultTableModel) jTableDisciplinas.getModel()).removeRow(linhaselecionada);
        
        gerenciardisciplinas.removerDisciplinas(NomeDisciplina);
        
    }//GEN-LAST:event_jBRemoverActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
         
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTableDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDisciplinasMouseClicked
            

    }//GEN-LAST:event_jTableDisciplinasMouseClicked

    private void jBPesquisarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarDisciplinasActionPerformed
        
        String NomeDisciplina = jTPesquisarDisciplinas.getText();
        System.out.println(NomeDisciplina);
        gerenciardisciplinas.consultarDisciplinas(NomeDisciplina);
        
        limpaTabela();
        
        for (Disciplinas elementoDisciplinas: Disciplinas.ListaDisciplinas) {
            if (elementoDisciplinas.getNomeDisciplina().equalsIgnoreCase(NomeDisciplina)) {
                tableModel.addRow(new Object[]{elementoDisciplinas.getNomeDisciplina()});
            }
        }
        
    }//GEN-LAST:event_jBPesquisarDisciplinasActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
                
        String texto = "Digite o nome da materia";
        jTPesquisarDisciplinas.setText(texto);
        
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGerenciarDisciplinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarDisciplina;
    private javax.swing.JButton jBPesquisarDisciplinas;
    private javax.swing.JButton jBRemover;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTPesquisarDisciplinas;
    private javax.swing.JTable jTableDisciplinas;
    // End of variables declaration//GEN-END:variables
}
