/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetopoo;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class JFNotas extends javax.swing.JFrame {

    String Usuario;
    Notas notas = new Notas();
    JFProfessor jfprofessor;
    JFCadastrarNotas jfcadastrarnotas;
    private DefaultTableModel tableModel;
    
    public JFNotas(String Usuario) {
        initComponents();
        this.Usuario = Usuario;
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nome Aluno");
        tableModel.addColumn("RA");
        tableModel.addColumn("Nota");
        jTableNotas.setModel(tableModel);
        tableModel.setRowCount(0);
    }
    
    public JFNotas() {
        initComponents();
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nome Aluno");
        tableModel.addColumn("RA");
        tableModel.addColumn("Nota");
        jTableNotas.setModel(tableModel);
        tableModel.setRowCount(0);
    }

    public void limpaTabela(){
        ((DefaultTableModel) jTableNotas.getModel()).setRowCount(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNotas = new javax.swing.JTable();
        jBAdicionar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jLNotas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableNotas);

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLNotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLNotas.setText("NOTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jBAdicionar)
                        .addGap(47, 47, 47)
                        .addComponent(jBAlterar)
                        .addGap(47, 47, 47)
                        .addComponent(jBVoltar)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLNotas)
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLNotas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAdicionar)
                    .addComponent(jBAlterar)
                    .addComponent(jBVoltar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        jfcadastrarnotas = new JFCadastrarNotas(Usuario);
        dispose();
        jfcadastrarnotas.setVisible(true);
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        
        limpaTabela();
        
        ArrayList<Notas> NotasProfessor = new ArrayList<>();
        NotasProfessor = notas.consultarNotas(Usuario);
        
        for (Notas elementoNotas: NotasProfessor) {
            tableModel.addRow(new Object[]{elementoNotas.getAlunoNome(),elementoNotas.getAlunoRA(),elementoNotas.getNota()});
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        jfprofessor = new JFProfessor(Usuario);
        dispose();
        jfprofessor.setVisible(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        
        int linhaselecionada = jTableNotas.getSelectedRow();
        String RA = jTableNotas.getValueAt(linhaselecionada, 1).toString();
        
        JFAlterarNotas jfalterarnotas = new JFAlterarNotas(Usuario, RA);
        jfalterarnotas.setVisible(true);
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setLocationRelativeTo(null);
        
        limpaTabela();
        
        ArrayList<Notas> NotasProfessor = new ArrayList<>();
        NotasProfessor = notas.consultarNotas(Usuario);
        
        for (Notas elementoNotas: NotasProfessor) {
            tableModel.addRow(new Object[]{elementoNotas.getAlunoNome(),elementoNotas.getAlunoRA(),elementoNotas.getNota()});
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLNotas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNotas;
    // End of variables declaration//GEN-END:variables
}
